# Generated by Django 2.2.12 on 2020-05-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('febreModerada', models.IntegerField()),
                ('febreAlta', models.IntegerField()),
                ('tossePersistente', models.IntegerField()),
                ('tosseSeca', models.IntegerField()),
                ('faltaDeAr', models.IntegerField()),
                ('dificuldadeRespirar', models.IntegerField()),
                ('problemaGastrico', models.IntegerField()),
                ('diarreia', models.IntegerField()),
                ('suspeitaCorona', models.IntegerField()),
            ],
        ),
    ]
