# Generated by Django 2.2.12 on 2020-05-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='suspeitaCorona',
            field=models.IntegerField(null=True),
        ),
    ]
